# ========== DEFAULT PROFILE (dev) ==========
# Usa application-dev.properties por padrão
spring.profiles.active=dev
spring.application.name=wofertas
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo=DEBUG